const SHOP_DATA = [
  {
    title: 'Swimsuits',
    items: [
      {
        id: 1,
        name: 'FARM RIO STRAPLESS SWIMSUIT',
        imageUrl: 'https://images.urbndata.com/is/image/Anthropologie/4142952480026_090_b3?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=540',
        SKU: 'b8dEF',
        price: 19.99,
      },
      {
        id: 2,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://www.swimsuitsforall.com/dw/image/v2/BBKT_PRD/on/demandware.static/-/Sites-masterCatalog_Swimsuitsforall/default/dw05e4d87d/images/hi-res/2466_10352_mc_1138.jpg?sw=653&sh=940&sm=fit&q=90&strip=false',
        SKU: '1038351',
        price: 56.28,
      },
      {
        id: 3,
        name: 'Boden Panel Underwire Swimsuit',
        imageUrl: 'https://themomedit.com/wp-content/uploads/2024/02/Boden-Panel-Underwire-Swimsuit-Navy_-Ivory-Stripe-677x1024.jpg',
        SKU: 'BPUSNIStr',
        price: 35,
      },
      {
        id: 4,
        name: 'Beach Riot Celine Ribbed One-Piece',
        imageUrl: 'https://themomedit.com/wp-content/uploads/2024/02/Beach-Riot-Celine-Ribbed-One-Piece-875x1024.jpg',
        SKU: 'BRCROP',
        price: 25,
      },
      {
        id: 5,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        SKU: 'YTjW3vF',
        price: 18,
      },
      {
        id: 6,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        SKU: 'rKBDvJX',
        price: 14,
      },
      {
        id: 7,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        SKU: 'bLB646Z',
        price: 18,
      },
      {
        id: 8,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        SKU: '1f2nWMM',
        price: 14,
      },
      {
        id: 9,
        name: 'Lace Up One Piece Swimsuit',
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        SKU: 'X2VJP2W',
        price: 16,
      },
    ],
  },
  {
    title: 'Hats',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        SKU: 'ZYW3VTp',
        price: 25,
      },
      {
        id: 2,
        name: 'Blue Beanie',
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        SKU: 'ypkgK0X',
        price: 18,
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        SKU: 'QdJwgmp',
        price: 35,
      },
      {
        id: 4,
        name: 'Grey Brim',
        imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
        SKU: 'RjBLWxB',
        price: 25,
      },
      {
        id: 5,
        name: 'Green Beanie',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        SKU: 'YTjW3vF',
        price: 18,
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        SKU: 'rKBDvJX',
        price: 14,
      },
      {
        id: 7,
        name: 'Red Beanie',
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        SKU: 'bLB646Z',
        price: 18,
      },
      {
        id: 8,
        name: 'Wolf Cap',
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        SKU: '1f2nWMM',
        price: 14,
      },
      {
        id: 9,
        name: 'Blue Snapback',
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        SKU: 'X2VJP2W',
        price: 16,
      },
    ],
  },
  {
    title: 'Sneakers',
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        SKU: '0s3pdnc',
        price: 220,
      },
      {
        id: 11,
        name: 'Adidas Yeezy',
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        SKU: 'dJbG1cT',
        price: 280,
      },
      {
        id: 12,
        name: 'Black Converse',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        SKU: 'bPmVXyP',
        price: 110,
      },
      {
        id: 13,
        name: 'Nike White AirForce',
        imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        SKU: '1RcFPk0',
        price: 160,
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
        SKU: 'QcvzydB',
        price: 160,
      },
      {
        id: 15,
        name: 'Nike Brown High Tops',
        imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        SKU: 'fMTV342',
        price: 160,
      },
      {
        id: 16,
        name: 'Air Jordan Limited',
        imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        SKU: 'w4k6Ws9',
        price: 190,
      },
      {
        id: 17,
        name: 'Timberlands',
        imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        SKU: 'Mhh6wBg',
        price: 200,
      },
    ],
  },
  {
    title: 'Jackets',
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        SKU: 'XzcwL5s',
        price: 125,
      },
      {
        id: 19,
        name: 'Blue Jean Jacket',
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        SKU: 'mJS6vz0',
        price: 90,
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        SKU: 'N71k1ML',
        price: 90,
      },
      {
        id: 21,
        name: 'Brown Shearling',
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        SKU: 's96FpdP',
        price: 165,
      },
      {
        id: 22,
        name: 'Tan Trench',
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        SKU: 'M6hHc3F',
        price: 185,
      },
    ],
  },
  {
    title: 'Women',
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        SKU: '7CQVJNm',
        price: 25,
      },
      {
        id: 24,
        name: 'Floral Blouse',
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        SKU: '4W2DGKm',
        price: 20,
      },
      {
        id: 25,
        name: 'Floral Dress',
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        SKU: 'KV18Ysr',
        price: 80,
      },
      {
        id: 26,
        name: 'Red Dots Dress',
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        SKU: 'N3BN1bh',
        price: 80,
      },
      {
        id: 27,
        name: 'Striped Sweater',
        imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        SKU: 'KmSkMbH',
        price: 45,
      },
      {
        id: 28,
        name: 'Yellow Track Suit',
        imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        SKU: 'v1cvwNf',
        price: 135,
      },
      {
        id: 29,
        name: 'White Blouse',
        imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
        SKU: 'qBcrsJg',
        price: 20,
      },
    ],
  },
  {
    title: 'Men',
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        SKU: 'xJS0T3Y',
        price: 325,
      },
      {
        id: 31,
        name: 'Floral T-shirt',
        imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        SKU: 'qMQ75QZ',
        price: 20,
      },
      {
        id: 32,
        name: 'Black & White Longsleeve',
        imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        SKU: '55z32tw',
        price: 25,
      },
      {
        id: 33,
        name: 'Pink T-shirt',
        imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        SKU: 'RvwnBL8',
        price: 25,
      },
      {
        id: 34,
        name: 'Jean Long Sleeve',
        imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        SKU: 'VpW4x5t',
        price: 40,
      },
      {
        id: 35,
        name: 'Burgundy T-shirt',
        imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        SKU: 'mh3VM1f',
        price: 25,
      },
    ],
  },
];

export default SHOP_DATA;