const PRODUCTS = [
  {
    // Price-checking key-value pairs:
    //         id: "ZYW3VTp",
    // ! === SKU: "ZYW3VTp",
    //         price: 25,
    // Basic key-value pairs:
    //         id: 1,
    //         name: 'Brown Brim',
    //         imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    //         price: 25,
    // Full ProductPage key-value pairs:
    title: "ZYW3VTp",
    id: "ZYW3VTp",
    SKU: "ZYW3VTp",
    name: "Brown Brim",
    desc: `Brown Brim Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 35,
    type: "design-shop",
    brand: "Cowboy",
    colors: "brown",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Hats"],
  },
  {
    title: "ypkgK0X",
    id: "ypkgK0X",
    SKU: "ypkgK0X",
    name: "Blue Beanie",
    desc: `Blu Beanie... Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    img2: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    price: 18,
    oldPrice: 20,
    type: "featured-in-shop",
    brand: "Cowboy",
    colors: "brown",
    isAvailable: "In Stock",
    isAvailableNumber: 3,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Hats"],
  },
  {
    title: "QdJwgmp",
    id: "QdJwgmp",
    SKU: "QdJwgmp",
    name: "Brown Cowboy",
    desc: `Cowoys' favourite wear... Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    img2: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    price: 35,
    oldPrice: 35,
    type: "featured-in-shop",
    brand: "Cowboy",
    colors: "brown",
    isAvailable: "In Stock",
    isAvailableNumber: 3,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Hats"],
  },
  {
    title: "XzcwL5s",
    id: "XzcwL5s",
    SKU: "XzcwL5s",
    name: "Black Jean Shearling",
    desc: `Blak Jean Shearling... Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    img2: "https://www.forever21.com/dw/image/v2/BFKH_PRD/on/demandware.static/-/Sites-f21-master-catalog/default/dw8777dfa7/1_front_750/00470387-03.jpg?sw=1000&sh=1500",
    price: 125,
    oldPrice: 155,
    type: "featured-in-shop",
    brand: "Jeans",
    colors: "black",
    isAvailable: "In Stock",
    isAvailableNumber: 3,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
];

// SHAPE (with types):
// SKU;
// "XzcwL5s"(string);

// brand;
// "Jeans"(string);

// categories(array);
// 0;
// "Design SHOP Clothes"(string);

// colors;
// "black"(string);

// desc;
// "Black Jean Shearling"(string);

// img;
// "https://i.ibb.co/XzcwL5s/black-shearling.png"(string);

// img2;
// "https://www.forever21.com/dw/image/v2/BFKH_PRD/on/demandware.static/-/Sites-f21-master-catalog/default/dw8777dfa7/1_front_750/00470387-03.jpg?sw=1000&sh=1500"(
//   string
// );

// isAvailable;
// "In Stock"(string);

// isAvailableNumber;
// 3(number);

// isNew;
// false(boolean);

// isSale;
// true(boolean);

// name;
// "Black Jean Shearling"(string);

// oldPrice;
// 155(number);

// price;
// "125"(string);

// sub_category(array);

// 0;
// "Jackets"(string);

// type;
// ("featured-in-shop");

const SHOP_PRODUCTS = [
  {
    title: "gaggressiveprtshirtindividualxix",
    id: 13,
    SKU: "gaggressiveprtshirtindividualxix",
    name: "Individual XIX K.P. City white T-shirt",
    desc: `Individual XIX K.P. City white T-shirt - 
Sizing:

Length: XL(78cm) XXL(79cm)

Bust: XL(60cm) XXL(62cm)`,
    img: "https://storage.googleapis.com/sw-storage.appspot.com/Termek_kepek/Ruha/Polo/Individual/gorkorcsolya-polo-ruhazat-shirt-individual-kp-front.jpg",
    img2: "https://storage.googleapis.com/sw-storage.appspot.com/Termek_kepek/Ruha/Polo/Individual/gorkorcsolya-polo-ruhazat-shirt-individual-kp-back.jpg",
    price: 17,
    oldPrice: 25.63,
    type: "design-shop",
    brand: "Individual",
    colors: "white",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: true,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sportswear"],
  },
  {
    title: "b8dEF",
    id: 12,
    SKU: "b8dEF",
    name: "FARM RIO STRAPLESS SWIMSUIT",
    desc: `Farm Rio Strapless Swimsuit - Last but definitely not least, Shana’s pick by Farm Rio. When I first saw this suit I thought the pattern was super playful but still wearable. Shana was shocked when she tried it on and loved.`,
    img: "https://images.urbndata.com/is/image/Anthropologie/4142952480026_090_b3?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=540",
    img2: "https://images.urbndata.com/is/image/Anthropologie/4142952480026_090_b2?$a15-pdp-detail-shot$&fit=constrain&fmt=webp&qlt=80&wid=540",
    price: 19,
    oldPrice: 25.99,
    type: "design-shop",
    brand: "Farm Rio",
    colors: "white",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "1038351",
    id: 14,
    SKU: "1038351",
    name: "Lace Up One Piece Swimsuit",
    desc: `Beach Riot swimsuits are bizarrely comfortable and fit great (S can vouch for this, and reviewers agree). This one comes in so many pretty colors, but there’s nothing like a pop of red for summatime. I am eyeing all the blue shades too, though.`,
    img: "https://www.swimsuitsforall.com/dw/image/v2/BBKT_PRD/on/demandware.static/-/Sites-masterCatalog_Swimsuitsforall/default/dw05e4d87d/images/hi-res/2466_10352_mc_1138.jpg?sw=653&sh=940&sm=fit&q=90&strip=false",
    img2: "https://cdn-fsly.yottaa.net/5bc4b5332bb0ac7822b9c2c8/www.swimsuitsforall.com/v~4b.5ca/dw/image/v2/BBKT_PRD/on/demandware.static/-/Sites-masterCatalog_Swimsuitsforall/default/dwb90ab981/images/on-hover/2466_10352_ma_0001.jpg?sw=653&sh=940&sm=fit&q=90&strip=false&yocs=1e_1h_",
    price: 56,
    oldPrice: 80.4,
    type: "design-shop",
    brand: "Swimsuitsforall",
    colors: "black/white/red/blue/purple",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "BPUSNIStr",
    id: 15,
    SKU: "BPUSNIStr",
    name: "Boden Panel Underwire Swimsuit",
    desc: `This is the best striped swimsuit I’ve found so far. It feels fresh, but still classic. Bonus points to Boden for pairing it with that bright green button-up (I love it so much). Boden also happens to make some of Laura’s favorite swimsuits.`,
    img: "https://themomedit.com/wp-content/uploads/2024/02/Boden-Panel-Underwire-Swimsuit-Navy_-Ivory-Stripe-677x1024.jpg",
    img2: "https://themomedit.com/wp-content/uploads/2024/02/Floral-Print-Shirred-Cutout-One-Piece-Swimsuit-Cupshe-800x1024.jpg",
    price: 35,
    oldPrice: 40,
    type: "design-shop",
    brand: "Farm Rio",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 15,
    isNew: true,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "BRCROP",
    id: 16,
    SKU: "BRCROP",
    name: "Beach Riot Celine Ribbed One-Piece",
    desc: `Beach Riot swimsuits are bizarrely comfortable and fit great (S can vouch for this, and reviewers agree). This one comes in so many pretty colors, but there’s nothing like a pop of red for summatime. I am eyeing all the blue shades too, though.`,
    img: "https://themomedit.com/wp-content/uploads/2024/02/Beach-Riot-Celine-Ribbed-One-Piece-875x1024.jpg",
    img2: "https://themomedit.com/wp-content/uploads/2024/02/LSPACE-Ribbed-Bree-One-Piece-Swimsuit-726x1024.jpg",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Farm Rio",
    colors: "red/green",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "IBGS1706646505",
    id: 17,
    SKU: "IBGS1706646505",
    name: "Imagine Solo D-F Cup Bikini Top - Imagine / Snow",
    desc: `Imagine Solo D-F Cup Bikini Top - Imagine / Snow - Last but definitely not least, Shana’s pick by Farm Rio. When I first saw this suit I thought the pattern was super playful but still wearable. Shana was shocked when she tried it on and loved.`,
    img: "https://www.bodyglove.com/cdn/shop/files/39-63815D_IMAGINE_SOLODFCUPTOP_LIFESTYLE2_1000x.jpg?v=1710272888",
    img2: "https://www.bodyglove.com/cdn/shop/files/3963815D_585Back2_1000x.jpg?v=1710272885",
    price: 69,
    oldPrice: 80.99,
    type: "design-shop",
    brand: "Farm Rio",
    colors: "white",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "CUPSHEOSCOOPS",
    id: 18,
    SKU: "CUPSHEOSCOOPS",
    name: "CUPSHE One Shoulder Cut Out One-piece Swimsuit",
    desc: `CUPSHE One Shoulder Cut Out One-piece Swimsuit - Last but definitely not least, Shana’s pick by Farm Rio. When I first saw this suit I thought the pattern was super playful but still wearable. Shana was shocked when she tried it on and loved.`,
    img: "https://ae01.alicdn.com/kf/H846b68f5691f405c8d714831cce17f73h/CUPSHE-One-Shoulder-Cut-Out-One-piece-Swimsuit-Women-Beach-Solid-Brown-Bathing-Suit-Swimwear-2023.jpg",
    img2: "https://di2ponv0v5otw.cloudfront.net/posts/2022/06/20/62b097bdff7c5a06c9b0f5d6/m_62b098e012d8804a3115a893.jpg",
    price: 62,
    oldPrice: 125.98,
    type: "design-shop",
    brand: "CUPSHE",
    colors: "white",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: true,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "OSFPHBBS1600128272496",
    id: 19,
    SKU: "OSFPHBBS1600128272496",
    name: "One Shoulder Floral Print Hollow Backless Beachwear Swimsuit Swimwear",
    desc: `One Shoulder Floral Print Hollow Backless Beachwear Swimsuit Swimwear Big Size Bikinis One Piece for Plus Size Women.`,
    img: "https://s.alicdn.com/@sc04/kf/H1ed7663503804b66b0a0bd29dc113329o.jpg",
    img2: "https://s.alicdn.com/@sc04/kf/H935cc6d164bd492aabb84819ded6693ce.jpg",
    price: 50,
    oldPrice: 125.99,
    type: "design-shop",
    brand: "Farm Rio",
    colors: "blue",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: true,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "SBSWSDHB972280638",
    id: 20,
    SKU: "SBSWSDHB972280638",
    name: "Summer Beach Sunshine Womens Swimwear designer high-end Bikini",
    desc: `Summer Beach Sunshine Womens Swimwear designer high-end Bikini C letter Diamond ing sexy one-piece swimsuit two-piece bikinis. brazilian string thong,original bikinis,reversible swimwear,pink black leopard print,dhl women suits,flower lace up bikini set,wrap top white,crossover bra,cropped shell,open bikini hot.`,
    img: "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/s/23/2a009a06-efce-450b-adde-66b37bac3da6.jpg",
    img2: "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/s/23/69abbfd3-9381-4539-83b8-b899e8ca1e54.jpg",
    price: 20,
    oldPrice: 25.99,
    type: "design-shop",
    brand: "Swimwear",
    colors: "white",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Swimsuits"],
  },
  {
    title: "ZYW3VTp",
    id: 21,
    SKU: "ZYW3VTp",
    name: "Brown Brim",
    desc: `Brown Brim - Unisex  Thin leather summer hat, Organic leather brim, Unisex hat, Summer apparel`,
    img: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    img2: "https://images.pexels.com/photos/4559830/pexels-photo-4559830.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "ypkgK0X",
    id: 22,
    SKU: "ypkgK0X",
    name: "Blue Beanie",
    desc: `Blue Beanie - Unisex WOOL BEANIE, Thick wool winter hat, Knit winter hat in gray, Organic wool beanie, Unisex hat, Winter apparel`,
    img: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    img2: "https://www.letocollection.com/cdn/shop/products/slouch-waffle-knit-beanie-blue-cute-497.jpg?v=1665610005",
    price: 18,
    oldPrice: 18,
    type: "design-shop",
    brand: "Leto",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "QdJwgmp",
    id: 9,
    SKU: "QdJwgmp",
    name: "Brown Cowboy",
    desc: `Brown Cowboy Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 35,
    oldPrice: 35,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  // TODO: Here we are!
  // IN PROCESS:->
  {
    title: "RjBLWxB",
    id: "RjBLWxB",
    SKU: "RjBLWxB",
    name: "Grey Brim",
    desc: `Grey Brim Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "YTjW3vF",
    id: "YTjW3vF",
    SKU: "YTjW3vF",
    name: "Green Beanie",
    desc: `Green Beanie Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 18,
    oldPrice: 18,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "rKBDvJX",
    id: "rKBDvJX",
    SKU: "rKBDvJX",
    name: "Palm Tree Cap",
    desc: `Palm Tree Cap Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 14,
    oldPrice: 14,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "bLB646Z",
    id: "bLB646Z",
    SKU: "bLB646Z",
    name: "Red Beanie",
    desc: `Red Beanie Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/bLB646Z/red-beanie.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 18,
    oldPrice: 18,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "1f2nWMM",
    id: "1f2nWMM",
    SKU: "1f2nWMM",
    name: "Wolf Cap",
    desc: `Wolf Cap Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 14,
    oldPrice: 14,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "X2VJP2W",
    id: "X2VJP2W",
    SKU: "X2VJP2W",
    name: "Blue Snapback",
    desc: `Blue Snapback Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 16,
    oldPrice: 16,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Hats"],
  },
  {
    title: "0s3pdnc",
    id: 11,
    SKU: "0s3pdnc",
    name: "Adidas NMD",
    desc: `Adidas NMD Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 220,
    oldPrice: 220,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "dJbG1cT",
    id: "dJbG1cT",
    SKU: "dJbG1cT",
    name: "Adidas Yeezy",
    desc: `Adidas Yeezy Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/dJbG1cT/yeezy.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 280,
    oldPrice: 280,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "bPmVXyP",
    id: "bPmVXyP",
    SKU: "bPmVXyP",
    name: "Black Converse",
    desc: `Black Converse Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/bPmVXyP/black-converse.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 110,
    oldPrice: 110,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "1RcFPk0",
    id: "1RcFPk0",
    SKU: "1RcFPk0",
    name: "Nike White AirForce",
    desc: `Nike White AirForce Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 160,
    oldPrice: 160,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "QcvzydB",
    id: "QcvzydB",
    SKU: "QcvzydB",
    name: "Nike Red High Tops",
    desc: `Nike Red High Tops Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/QcvzydB/nikes-red.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 160,
    oldPrice: 160,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "fMTV342",
    id: "fMTV342",
    SKU: "fMTV342",
    name: "Nike Brown High Tops",
    desc: `Nike Brown High Tops Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/fMTV342/nike-brown.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 160,
    oldPrice: 160,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "w4k6Ws9",
    id: "w4k6Ws9",
    SKU: "w4k6Ws9",
    name: "Air Jordan Limited",
    desc: `Air Jordan Limited Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 190,
    oldPrice: 190,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "Mhh6wBg",
    id: "Mhh6wBg",
    SKU: "Mhh6wBg",
    name: "Timberlands",
    desc: `Timberlands Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    img2: "https://images.pexels.com/photos/1280064/pexels-photo-1280064.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 200,
    oldPrice: 200,
    type: "design-shop",
    brand: "Adidas-Nike",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Accessories"],
    sub_category: ["Sneakers"],
  },
  {
    title: "XzcwL5s",
    id: 10,
    SKU: "XzcwL5s",
    name: "Black Jean Shearling",
    desc: `Black Jean Shearling Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 125,
    oldPrice: 125,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
  {
    title: "mJS6vz0",
    id: "mJS6vz0",
    SKU: "mJS6vz0",
    name: "Blue Jean Jacket",
    desc: `Blue Jean Jacket Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 90,
    oldPrice: 90,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
  {
    title: "N71k1ML",
    id: "N71k1ML",
    SKU: "N71k1ML",
    name: "Grey Jean Jacket",
    desc: `Grey Jean Jacket Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 90,
    oldPrice: 90,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
  {
    title: "s96FpdP",
    id: "s96FpdP",
    SKU: "s96FpdP",
    name: "Brown Shearling",
    desc: `Brown Shearling Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 165,
    oldPrice: 165,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
  {
    title: "M6hHc3F",
    id: "M6hHc3F",
    SKU: "M6hHc3F",
    name: "Tan Trench",
    desc: `Tan Trench Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 185,
    oldPrice: 185,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Jackets"],
  },
  {
    title: "7CQVJNm",
    id: "7CQVJNm",
    SKU: "7CQVJNm",
    name: "Blue Tanktop",
    desc: `Blue Tanktop Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "KV18Ysr",
    id: "KV18Ysr",
    SKU: "KV18Ysr",
    name: "Floral Dress",
    desc: `Floral Dress Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 80,
    oldPrice: 80,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "N3BN1bh",
    id: "N3BN1bh",
    SKU: "N3BN1bh",
    name: "Red Dots Dress",
    desc: `Red Dots Dress Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 80,
    oldPrice: 80,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "KmSkMbH",
    id: "KmSkMbH",
    SKU: "KmSkMbH",
    name: "Striped Sweater",
    desc: `Striped Sweater Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 45,
    oldPrice: 45,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "v1cvwNf",
    id: "v1cvwNf",
    SKU: "v1cvwNf",
    name: "Yellow Track Suit",
    desc: `Yellow Track Suit Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 135,
    oldPrice: 135,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "qBcrsJg",
    id: "qBcrsJg",
    SKU: "qBcrsJg",
    name: "White Blouse",
    desc: `White Blouse Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/qBcrsJg/white-vest.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 20,
    oldPrice: 20,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Women"],
  },
  {
    title: "xJS0T3Y",
    id: "xJS0T3Y",
    SKU: "xJS0T3Y",
    name: "Camo Down Vest",
    desc: `Camo Down Vest Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 325,
    oldPrice: 325,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
  {
    title: "qMQ75QZ",
    id: "qMQ75QZ",
    SKU: "qMQ75QZ",
    name: "Floral T-shirt",
    desc: `Floral T-shirt Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 20,
    oldPrice: 20,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
  {
    title: "55z32tw",
    id: "55z32tw",
    SKU: "55z32tw",
    name: "Black & White Longsleeve",
    desc: `Black & White Longsleeve Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/55z32tw/long-sleeve.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
  {
    title: "RvwnBL8",
    id: "RvwnBL8",
    SKU: "RvwnBL8",
    name: "Pink T-shirt",
    desc: `Pink T-shirt Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
  {
    title: "VpW4x5t",
    id: "VpW4x5t",
    SKU: "VpW4x5t",
    name: "Jean Long Sleeve",
    desc: `Jean Long Sleeve Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 40,
    oldPrice: 40,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
  {
    title: "mh3VM1f",
    id: "mh3VM1f",
    SKU: "mh3VM1f",
    name: "Burgundy T-shirt",
    desc: `Burgundy T-shirt Solid Slim Fit Single Breasted Formal Blazer, has long sleeves, notched lapel collar and button closure
    Blue Solid Slim Fit Trousers, has 2 pockets and secured with hook and bar closure`,
    img: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    img2: "https://images.pexels.com/photos/6347552/pexels-photo-6347552.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25,
    oldPrice: 25,
    type: "design-shop",
    brand: "Zara",
    colors: "all",
    isAvailable: "In Stock",
    isAvailableNumber: 5,
    isNew: false,
    isSale: true,
    categories: ["Design SHOP Clothes"],
    sub_category: ["Men"],
  },
];

export default SHOP_PRODUCTS;
